name: _
publish_to: none
environment:
  sdk: ^3.9.0

workspace:
  - packages/meovm
  - packages/meovm_api
  - packages/meovm_gen
  - packages/meovm_riverpod
  - packages/meovm_gen_test
  - packages/meovm_bloc
  - packages/meovm/example
  - packages/meovm_riverpod/example
  - packages/meovm_bloc/example
  - packages/meovm_lint
