name: meovm
description: "A MVVM framework for Flutter"
version: 0.0.1

environment:
  sdk: ^3.9.0
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  graphs: ^2.3.2
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: