name: meovm_api
description: "Flutter independent API for meovm — lightweight MVVM framework for Flutter. Built-in dependencies between members, bunch of built-in members for common use cases, and minimum boilerplate approach."
version: 1.1.1
repository: https://github.com/da-cat7976/meovm
issue_tracker: https://github.com/da-cat7976/meovm/issues

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.0.0
