name: meovm_gen
description: "A code generator for meovm — lightweight MVVM framework for Flutter. Built-in dependencies between members, bunch of built-in members for common use cases, and minimum boilerplate approach."
version: 1.0.0
repository: https://github.com/da-cat7976/meovm
issue_tracker: https://github.com/da-cat7976/meovm/issues

environment:
  sdk: ^3.9.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  code_builder: ^4.10.1
  build: ^3.0.0
  build_resolvers: ^3.0.0
  build_config: ^1.1.2
  dart_style: ^3.1.1
  string_scanner: ^1.4.1
  analyzer: ">=7.0.0 <9.0.0"
  source_span: ^1.10.1
  package_config: ^2.2.0
  path: ^1.9.1
  loggy: ^2.0.3
  meovm_api: ^1.0.0
  source_gen: ^3.0.0
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.5.4
  lints: ^6.0.0
  test: ^1.21.0
