name: meovm_riverpod
description: "Riverpod integration for meovm"
version: 0.0.1
# TODO: Remove after pub release
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  # TODO: Remove path dependency after pub release
  meovm:
    path: ../../
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
