name: meovm_lint
description: "A linter for meovm — lightweight MVVM framework for Flutter. Built-in dependencies between members, bunch of built-in members for common use cases, and minimum boilerplate approach."
version: 1.2.0
repository: https://github.com/da-cat7976/meovm
issue_tracker: https://github.com/da-cat7976/meovm/issues

resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  analysis_server_plugin: 0.3.18
  analyzer: ^13.3.0
  source_gen: ^4.2.4

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.1
